In [1]:
import numpy as np
import pandas as pd
import os
import glob

pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)

In [11]:
df_test_pitch = pd.read_csv('../yakiu_rawdata/test_pitch.csv')
df_test_player = pd.read_csv('../yakiu_rawdata/test_player.csv')
df_train_pitch = pd.read_csv('../yakiu_rawdata/test_pitch.csv')
df_train_player = pd.read_csv('../yakiu_rawdata/test_player.csv')
df_sample = pd.read_csv('../yakiu_rawdata/sample_submit_ball_type.csv')

# プレイデータの加工

In [12]:
df_test_pitch

,データ内連番,年度,試合ID,試合内連番,試合内投球数,日付,時刻,ホームチームID,アウェイチームID,球場ID,球場名,試合種別詳細,イニング,表裏,イニング内打席数,打席内投球数,投手ID,投手チームID,投手投球左右,投手役割,投手登板順,投手試合内対戦打者数,投手試合内投球数,投手イニング内投球数,打者ID,打者チームID,打者打席左右,打者打順,打者守備位置,打者試合内打席数,プレイ前ホームチーム得点数,プレイ前アウェイチーム得点数,プレイ前アウト数,プレイ前ボール数,プレイ前ストライク数,プレイ前走者状況,一塁走者ID,二塁走者ID,三塁走者ID,捕手ID,一塁手ID,二塁手ID,三塁手ID,遊撃手ID,左翼手ID,中堅手ID,右翼手ID,成績対象投手ID,成績対象打者ID
0,0,2018,2018033001,1,1,2018-03-30,18:03:00,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,1,1,1200041,1,右,先発,1,1,1,1,1500086,5,左,1,中,1,0,0,0,0,0,___,NaN,NaN,NaN,1300027,1400101,1600059,1200136,700003,1600184,600037,900397,1200041,1500086
1,1,2018,2018033001,2,2,2018-03-30,18:03:39,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,2,1,1200041,1,右,先発,1,2,2,2,400001,5,左,2,二,1,0,0,1,0,0,___,NaN,NaN,NaN,1300027,1400101,1600059,1200136,700003,1600184,600037,900397,1200041,400001
2,2,2018,2018033001,3,3,2018-03-30,18:03:57,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,2,2,1200041,1,右,先発,1,2,3,3,400001,5,左,2,二,1,0,0,1,0,1,___,NaN,NaN,NaN,1300027,1400101,1600059,1200136,700003,1600184,600037,900397,1200041,400001
3,3,2018,2018033001,4,4,2018-03-30,18:04:40,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,3,1,1200041,1,右,先発,1,3,4,4,400057,5,左,3,右,1,0,0,2,0,0,___,NaN,NaN,NaN,1300027,1400101,1600059,1200136,700003,1600184,600037,900397,1200041,400057
4,4,2018,2018033001,5,5,2018-03-30,18:04:56,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,3,2,1200041,1,右,先発,1,3,5,5,400057,5,左,3,右,1,0,0,2,1,0,___,NaN,NaN,NaN,1300027,1400101,1600059,1200136,700003,1600184,600037,900397,1200041,400057
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521645,521645,2019,2019093001,289,285,2019-09-30,21:10:05,5,4,5,甲子園,セ・リーグ公式戦,9,表,3,8,11807,5,右,救援,6,3,17,17,700034,4,右,4,一,2,3,0,1,1,2,_2_,NaN,1700103.0,NaN,1300073,1300072,1400172,1600113,400001,11771,1800065,1500086,11807,700034
521646,521646,2019,2019093001,290,286,2019-09-30,21:10:53,5,4,5,甲子園,セ・リーグ公式戦,9,表,4,1,11807,5,右,救援,6,4,18,18,1100069,4,左,5,三,4,3,0,2,0,0,_2_,NaN,1700103.0,NaN,1300073,1300072,1400172,1600113,400001,11771,1800065,1500086,11807,1100069
521647,521647,2019,2019093001,291,287,2019-09-30,21:11:21,5,4,5,甲子園,セ・リーグ公式戦,9,表,4,2,11807,5,右,救援,6,4,19,19,1100069,4,左,5,三,4,3,0,2,0,1,_2_,NaN,1700103.0,NaN,1300073,1300072,1400172,1600113,400001,11771,1800065,1500086,11807,1100069
521648,521648,2019,2019093001,292,288,2019-09-30,21:12:05,5,4,5,甲子園,セ・リーグ公式戦,9,表,4,3,11807,5,右,救援,6,4,20,20,1100069,4,左,5,三,4,3,0,2,0,2,_2_,NaN,1700103.0,NaN,1300073,1300072,1400172,1600113,400001,11771,1800065,1500086,11807,1100069
521649,521649,2019,2019093001,293,289,2019-09-30,21:12:48,5,4,5,甲子園,セ・リーグ公式戦,9,表,4,4,11807,5,右,救援,6,4,21,21,1100069,4,左,5,三,4,3,0,2,1,2,_2_,NaN,1700103.0,NaN,1300073,1300072,1400172,1600113,400001,11771,1800065,1500086,11807,1100069

In [13]:
df_train_pitch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521650 entries, 0 to 521649
Data columns (total 49 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   データ内連番          521650 non-null  int64
 1   年度              521650 non-null  int64
 2   試合ID            521650 non-null  int64
 3   試合内連番           521650 non-null  int64
 4   試合内投球数          521650 non-null  int64
 5   日付              521650 non-null  object
 6   時刻              521650 non-null  object
 7   ホームチームID        521650 non-null  int64
 8   アウェイチームID       521650 non-null  int64
 9   球場ID            521650 non-null  int64
 10  球場名             521650 non-null  object
 11  試合種別詳細          521650 non-null  object
 12  イニング            521650 non-null  int64
 13  表裏              521650 non-null  object
 14  イニング内打席数        521650 non-null  int64
 15  打席内投球数          521650 non-null  int64
 16  投手ID            521650 non-null  int64
 17  投手チームID         521650 non-null  int64
 18  投手投球左右          521650 non-null  object
 19  投手役割            521650 non-null  object
 20  投手登板順           521650 non-null  int64
 21  投手試合内対戦打者数      521650 non-null  int64
 22  投手試合内投球数        521650 non-null  int64
 23  投手イニング内投球数      521650 non-null  int64
 24  打者ID            521650 non-null  int64
 25  打者チームID         521650 non-null  int64
 26  打者打席左右          521650 non-null  object
 27  打者打順            521650 non-null  int64
 28  打者守備位置          521650 non-null  object
 29  打者試合内打席数        521650 non-null  int64
 30  プレイ前ホームチーム得点数   521650 non-null  int64
 31  プレイ前アウェイチーム得点数  521650 non-null  int64
 32  プレイ前アウト数        521650 non-null  int64
 33  プレイ前ボール数        521650 non-null  int64
 34  プレイ前ストライク数      521650 non-null  int64
 35  プレイ前走者状況        521650 non-null  object
 36  一塁走者ID          160789 non-null  float64
 37  二塁走者ID          103655 non-null  float64
 38  三塁走者ID          53101 non-null   float64
 39  捕手ID            521650 non-null  int64
 40  一塁手ID           521650 non-null  int64
 41  二塁手ID           521650 non-null  int64
 42  三塁手ID           521650 non-null  int64
 43  遊撃手ID           521650 non-null  int64
 44  左翼手ID           521650 non-null  int64
 45  中堅手ID           521650 non-null  int64
 46  右翼手ID           521650 non-null  int64
 47  成績対象投手ID        521650 non-null  int64
 48  成績対象打者ID        521650 non-null  int64
dtypes: float64(3), int64(36), object(10)
memory usage: 195.0+ MB

In [14]:
df_train_pitch2 =  df_train_pitch.drop(['年度','一塁手ID','二塁手ID','三塁手ID','遊撃手ID','左翼手ID','中堅手ID','左翼手ID'], axis=1)

In [15]:
df_train_pitch2.head(5)

,データ内連番,試合ID,試合内連番,試合内投球数,日付,時刻,ホームチームID,アウェイチームID,球場ID,球場名,試合種別詳細,イニング,表裏,イニング内打席数,打席内投球数,投手ID,投手チームID,投手投球左右,投手役割,投手登板順,投手試合内対戦打者数,投手試合内投球数,投手イニング内投球数,打者ID,打者チームID,打者打席左右,打者打順,打者守備位置,打者試合内打席数,プレイ前ホームチーム得点数,プレイ前アウェイチーム得点数,プレイ前アウト数,プレイ前ボール数,プレイ前ストライク数,プレイ前走者状況,一塁走者ID,二塁走者ID,三塁走者ID,捕手ID,右翼手ID,成績対象投手ID,成績対象打者ID
0,0,2018033001,1,1,2018-03-30,18:03:00,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,1,1,1200041,1,右,先発,1,1,1,1,1500086,5,左,1,中,1,0,0,0,0,0,___,NaN,NaN,NaN,1300027,900397,1200041,1500086
1,1,2018033001,2,2,2018-03-30,18:03:39,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,2,1,1200041,1,右,先発,1,2,2,2,400001,5,左,2,二,1,0,0,1,0,0,___,NaN,NaN,NaN,1300027,900397,1200041,400001
2,2,2018033001,3,3,2018-03-30,18:03:57,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,2,2,1200041,1,右,先発,1,2,3,3,400001,5,左,2,二,1,0,0,1,0,1,___,NaN,NaN,NaN,1300027,900397,1200041,400001
3,3,2018033001,4,4,2018-03-30,18:04:40,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,3,1,1200041,1,右,先発,1,3,4,4,400057,5,左,3,右,1,0,0,2,0,0,___,NaN,NaN,NaN,1300027,900397,1200041,400057
4,4,2018033001,5,5,2018-03-30,18:04:56,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,3,2,1200041,1,右,先発,1,3,5,5,400057,5,左,3,右,1,0,0,2,1,0,___,NaN,NaN,NaN,1300027,900397,1200041,400057

In [16]:
df_train_pitch2['count'] = df_train_pitch2[['プレイ前ストライク数', 'プレイ前ボール数', 'プレイ前アウト数']].apply(lambda x: '{}-{}-{}'.format(x[0], x[1], x[2]), axis=1)

In [17]:
df_train_pitch2['count']

0         0-0-0
1         0-0-1
2         1-0-1
3         0-0-2
4         0-1-2
          ...
521645    2-1-1
521646    0-0-2
521647    1-0-2
521648    2-0-2
521649    2-1-2
Name: count, Length: 521650, dtype: object

In [18]:
df_train_pitch2_h = df_train_pitch2.query('表裏=="表"')
df_train_pitch2_h['pitch_team_score'] = df_train_pitch2_h['プレイ前アウェイチーム得点数']-df_train_pitch2_h['プレイ前ホームチーム得点数']
df_train_pitch2_a = df_train_pitch2.query('表裏=="裏"')
df_train_pitch2_a['pitch_team_score'] = df_train_pitch2_a['プレイ前ホームチーム得点数']-df_train_pitch2_a['プレイ前アウェイチーム得点数']
df_train_pitch3 = pd.concat([df_train_pitch2_h,df_train_pitch2_a])
df_train_pitch3 =df_train_pitch3.sort_values('データ内連番')
df_train_pitch3

C:\Users\bono_\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\bono_\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,データ内連番,試合ID,試合内連番,試合内投球数,日付,時刻,ホームチームID,アウェイチームID,球場ID,球場名,試合種別詳細,イニング,表裏,イニング内打席数,打席内投球数,投手ID,投手チームID,投手投球左右,投手役割,投手登板順,投手試合内対戦打者数,投手試合内投球数,投手イニング内投球数,打者ID,打者チームID,打者打席左右,打者打順,打者守備位置,打者試合内打席数,プレイ前ホームチーム得点数,プレイ前アウェイチーム得点数,プレイ前アウト数,プレイ前ボール数,プレイ前ストライク数,プレイ前走者状況,一塁走者ID,二塁走者ID,三塁走者ID,捕手ID,右翼手ID,成績対象投手ID,成績対象打者ID,count,pitch_team_score
0,0,2018033001,1,1,2018-03-30,18:03:00,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,1,1,1200041,1,右,先発,1,1,1,1,1500086,5,左,1,中,1,0,0,0,0,0,___,NaN,NaN,NaN,1300027,900397,1200041,1500086,0-0-0,0
1,1,2018033001,2,2,2018-03-30,18:03:39,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,2,1,1200041,1,右,先発,1,2,2,2,400001,5,左,2,二,1,0,0,1,0,0,___,NaN,NaN,NaN,1300027,900397,1200041,400001,0-0-1,0
2,2,2018033001,3,3,2018-03-30,18:03:57,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,2,2,1200041,1,右,先発,1,2,3,3,400001,5,左,2,二,1,0,0,1,0,1,___,NaN,NaN,NaN,1300027,900397,1200041,400001,1-0-1,0
3,3,2018033001,4,4,2018-03-30,18:04:40,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,3,1,1200041,1,右,先発,1,3,4,4,400057,5,左,3,右,1,0,0,2,0,0,___,NaN,NaN,NaN,1300027,900397,1200041,400057,0-0-2,0
4,4,2018033001,5,5,2018-03-30,18:04:56,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,3,2,1200041,1,右,先発,1,3,5,5,400057,5,左,3,右,1,0,0,2,1,0,___,NaN,NaN,NaN,1300027,900397,1200041,400057,0-1-2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521645,521645,2019093001,289,285,2019-09-30,21:10:05,5,4,5,甲子園,セ・リーグ公式戦,9,表,3,8,11807,5,右,救援,6,3,17,17,700034,4,右,4,一,2,3,0,1,1,2,_2_,NaN,1700103.0,NaN,1300073,1500086,11807,700034,2-1-1,-3
521646,521646,2019093001,290,286,2019-09-30,21:10:53,5,4,5,甲子園,セ・リーグ公式戦,9,表,4,1,11807,5,右,救援,6,4,18,18,1100069,4,左,5,三,4,3,0,2,0,0,_2_,NaN,1700103.0,NaN,1300073,1500086,11807,1100069,0-0-2,-3
521647,521647,2019093001,291,287,2019-09-30,21:11:21,5,4,5,甲子園,セ・リーグ公式戦,9,表,4,2,11807,5,右,救援,6,4,19,19,1100069,4,左,5,三,4,3,0,2,0,1,_2_,NaN,1700103.0,NaN,1300073,1500086,11807,1100069,1-0-2,-3
521648,521648,2019093001,292,288,2019-09-30,21:12:05,5,4,5,甲子園,セ・リーグ公式戦,9,表,4,3,11807,5,右,救援,6,4,20,20,1100069,4,左,5,三,4,3,0,2,0,2,_2_,NaN,1700103.0,NaN,1300073,1500086,11807,1100069,2-0-2,-3
521649,521649,2019093001,293,289,2019-09-30,21:12:48,5,4,5,甲子園,セ・リーグ公式戦,9,表,4,4,11807,5,右,救援,6,4,21,21,1100069,4,左,5,三,4,3,0,2,1,2,_2_,NaN,1700103.0,NaN,1300073,1500086,11807,1100069,2-1-2,-3

In [19]:
df_date =df_train_pitch3['日付'].str.split('-', expand=True)
df_date

           0   1   2
0       2018  03  30
1       2018  03  30
2       2018  03  30
3       2018  03  30
4       2018  03  30
...      ...  ..  ..
521645  2019  09  30
521646  2019  09  30
521647  2019  09  30
521648  2019  09  30
521649  2019  09  30

[521650 rows x 3 columns]

In [20]:
df_date.rename(columns={0: 'year', 1: 'month',2:'day'}, inplace=True)
df_date = df_date.loc[:,['month']]
df_date = df_date.astype({'month':int})
df_date.head()

   month
0      3
1      3
2      3
3      3
4      3

In [21]:
df_train_pitch3 = pd.concat([df_train_pitch3,df_date],axis=1)

In [24]:
pitch_group = df_train_pitch3.groupby(['試合ID','イニング','表裏','イニング内打席数'])

In [23]:
lag_pitch = pd.DataFrame(pitch_group['球種'].shift(1))

KeyError: 'Column not found: 球種'

In [49]:
lag_pitch = lag_pitch.fillna(15)
lag_pitch = lag_pitch.rename(columns={'球種': 'lag_pitch'})
lag_pitch['lag_pitch'] = lag_pitch['lag_pitch']
lag_pitch = lag_pitch.astype('int64')
lag_pitch

        lag_pitch
0              15
1               0
2               0
3              15
4               0
...           ...
257112         15
257113          0
257114          0
257115          0
257116          0

[257117 rows x 1 columns]

In [50]:
df_train_pitch4 = pd.concat([df_train_pitch3,lag_pitch],axis=1)

In [25]:
pd.to_pickle(df_train_pitch3,'./df_test_pitch3.pkl')

In [53]:
df_train_pitch4 = pd.read_pickle('./df_test_pitch4.pkl')

In [27]:
df_train_pitch3.to_csv('./df_test_pitch4.csv')

# playerファイルの加工

In [28]:
df_train_player

,年度,チームID,チーム名,選手ID,選手名,育成選手F,背番号,位置,投,打,身長,体重,生年月日,出身高校ID,出身高校名,出身大学ID,出身大学名,社会人,ドラフト年,ドラフト種別,ドラフト順位,年俸,出身国,出身地,血液型
0,2018,1,巨人,11774,上原 浩治,0,11,投手,右,右,187,87,1975/4/3,1248,東海大仰星,1012,大阪体育大,NaN,1998.0,NaN,1.0,20000,日本,大阪,B
1,2018,1,巨人,12049,阿部 慎之助,0,10,内野手,右,左,180,97,1979/3/20,1114,安田学園,895,中央大,NaN,2000.0,NaN,1.0,21000,日本,千葉,A
2,2018,1,巨人,12107,杉内 俊哉,0,18,投手,左,左,175,82,1980/10/30,740,鹿児島実,0,不明,三菱重工長崎,2001.0,NaN,3.0,2500,日本,福岡,A
3,2018,1,巨人,12179,大竹 寛,0,17,投手,右,右,184,94,1983/5/21,179,浦和学院,0,不明,NaN,2001.0,NaN,1.0,5250,日本,埼玉,B
4,2018,1,巨人,400010,内海 哲也,0,26,投手,左,左,186,95,1982/4/29,385,敦賀気比,0,不明,東京ガス,2003.0,NaN,1.0,10000,日本,京都,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1841,2019,376,楽天,1800126,則本 佳樹,1,136,投手,右,左,174,79,1994/5/14,30099,北大津,1002,近畿大,山岸ロジスターズ,2018.0,育成選手,2.0,250,日本,滋賀,A
1842,2019,376,楽天,1800129,ブセニッツ,0,32,投手,右,右,185,81,1990/8/22,0,不明,0,不明,NaN,NaN,NaN,NaN,7000,アメリカ,不明,不明
1843,2019,376,楽天,1800132,ブラッシュ,0,69,外野手,右,右,196,106,1989/7/4,0,不明,0,不明,NaN,NaN,NaN,NaN,12000,アメリカ,不明,不明
1844,2019,376,楽天,1900006,ヒメネス,0,99,内野手,右,右,180,94,1988/1/18,0,不明,0,不明,NaN,NaN,NaN,NaN,1500,ドミニカ共和国,不明,不明
1845,2019,376,楽天,1900015,王 彦程,1,17,投手,左,左,180,82,2001/2/14,0,不明,0,不明,NaN,NaN,NaN,NaN,0,台湾,不明,不明

In [29]:
df_train_player2 = pd.DataFrame(df_train_player)

In [30]:
df_train_player['年齢'] = df_train_player['年度']-df_train_player['ドラフト年']

In [31]:
df_age = df_train_player['生年月日'].str.split('/',expand = True)
df_age.head()

      0   1   2
0  1975   4   3
1  1979   3  20
2  1980  10  30
3  1983   5  21
4  1982   4  29

In [32]:
df_age.rename(columns={0:'birth'},inplace=True)
df_age =df_age.drop([1,2],axis=1)
df_age

     birth
0     1975
1     1979
2     1980
3     1983
4     1982
...    ...
1841  1994
1842  1990
1843  1989
1844  1988
1845  2001

[1846 rows x 1 columns]

In [33]:
df_age.isnull().sum()

birth    0
dtype: int64

In [34]:
df_age = df_age.astype('int64')

In [35]:
df_train_player3 = pd.concat([df_train_player2,df_age],axis=1)

In [36]:
df_train_player3['age'] = df_train_player3['年度']-df_train_player3['birth']

In [37]:
df_train_player4 =df_train_player3.loc[:,['年度','選手ID','age']]

In [62]:
df_merge_test = pd.merge(df_train_pitch3,df_train_player4,left_on=['投手ID',right_on='選手ID',how='left')

In [63]:
df_merge2_test = df_merge_test.drop(['試合ID','時刻','ホームチームID','アウェイチームID','球場ID','球場名','試合種別詳細','イニング内打席数','投手ID','投手チームID','打者ID','打者チームID','プレイ前ホームチーム得点数','プレイ前アウェイチーム得点数','一塁走者ID','二塁走者ID','三塁走者ID','捕手ID','成績対象投手ID','成績対象打者ID','年度','選手ID'],axis=1)

In [43]:
pd.to_pickle(df_merge2_test,'df_merge2_test.pkl')

In [52]:
len(df_merge2_test)

1003191

In [55]:
df_train_pitch3

,データ内連番,試合ID,試合内連番,試合内投球数,日付,時刻,ホームチームID,アウェイチームID,球場ID,球場名,試合種別詳細,イニング,表裏,イニング内打席数,打席内投球数,投手ID,投手チームID,投手投球左右,投手役割,投手登板順,投手試合内対戦打者数,投手試合内投球数,投手イニング内投球数,打者ID,打者チームID,打者打席左右,打者打順,打者守備位置,打者試合内打席数,プレイ前ホームチーム得点数,プレイ前アウェイチーム得点数,プレイ前アウト数,プレイ前ボール数,プレイ前ストライク数,プレイ前走者状況,一塁走者ID,二塁走者ID,三塁走者ID,捕手ID,右翼手ID,成績対象投手ID,成績対象打者ID,count,pitch_team_score,month
0,0,2018033001,1,1,2018-03-30,18:03:00,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,1,1,1200041,1,右,先発,1,1,1,1,1500086,5,左,1,中,1,0,0,0,0,0,___,NaN,NaN,NaN,1300027,900397,1200041,1500086,0-0-0,0,3
1,1,2018033001,2,2,2018-03-30,18:03:39,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,2,1,1200041,1,右,先発,1,2,2,2,400001,5,左,2,二,1,0,0,1,0,0,___,NaN,NaN,NaN,1300027,900397,1200041,400001,0-0-1,0,3
2,2,2018033001,3,3,2018-03-30,18:03:57,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,2,2,1200041,1,右,先発,1,2,3,3,400001,5,左,2,二,1,0,0,1,0,1,___,NaN,NaN,NaN,1300027,900397,1200041,400001,1-0-1,0,3
3,3,2018033001,4,4,2018-03-30,18:04:40,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,3,1,1200041,1,右,先発,1,3,4,4,400057,5,左,3,右,1,0,0,2,0,0,___,NaN,NaN,NaN,1300027,900397,1200041,400057,0-0-2,0,3
4,4,2018033001,5,5,2018-03-30,18:04:56,1,5,1,東京ドーム,セ・リーグ公式戦,1,表,3,2,1200041,1,右,先発,1,3,5,5,400057,5,左,3,右,1,0,0,2,1,0,___,NaN,NaN,NaN,1300027,900397,1200041,400057,0-1-2,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521645,521645,2019093001,289,285,2019-09-30,21:10:05,5,4,5,甲子園,セ・リーグ公式戦,9,表,3,8,11807,5,右,救援,6,3,17,17,700034,4,右,4,一,2,3,0,1,1,2,_2_,NaN,1700103.0,NaN,1300073,1500086,11807,700034,2-1-1,-3,9
521646,521646,2019093001,290,286,2019-09-30,21:10:53,5,4,5,甲子園,セ・リーグ公式戦,9,表,4,1,11807,5,右,救援,6,4,18,18,1100069,4,左,5,三,4,3,0,2,0,0,_2_,NaN,1700103.0,NaN,1300073,1500086,11807,1100069,0-0-2,-3,9
521647,521647,2019093001,291,287,2019-09-30,21:11:21,5,4,5,甲子園,セ・リーグ公式戦,9,表,4,2,11807,5,右,救援,6,4,19,19,1100069,4,左,5,三,4,3,0,2,0,1,_2_,NaN,1700103.0,NaN,1300073,1500086,11807,1100069,1-0-2,-3,9
521648,521648,2019093001,292,288,2019-09-30,21:12:05,5,4,5,甲子園,セ・リーグ公式戦,9,表,4,3,11807,5,右,救援,6,4,20,20,1100069,4,左,5,三,4,3,0,2,0,2,_2_,NaN,1700103.0,NaN,1300073,1500086,11807,1100069,2-0-2,-3,9
521649,521649,2019093001,293,289,2019-09-30,21:12:48,5,4,5,甲子園,セ・リーグ公式戦,9,表,4,4,11807,5,右,救援,6,4,21,21,1100069,4,左,5,三,4,3,0,2,1,2,_2_,NaN,1700103.0,NaN,1300073,1500086,11807,1100069,2-1-2,-3,9

In [64]:
df_merge2_test

,データ内連番,試合内連番,試合内投球数,日付,イニング,表裏,打席内投球数,投手投球左右,投手役割,投手登板順,投手試合内対戦打者数,投手試合内投球数,投手イニング内投球数,打者打席左右,打者打順,打者守備位置,打者試合内打席数,プレイ前アウト数,プレイ前ボール数,プレイ前ストライク数,プレイ前走者状況,右翼手ID,count,pitch_team_score,month,age
0,0,1,1,2018-03-30,1,表,1,右,先発,1,1,1,1,左,1,中,1,0,0,0,___,900397,0-0-0,0,3,29
1,0,1,1,2018-03-30,1,表,1,右,先発,1,1,1,1,左,1,中,1,0,0,0,___,900397,0-0-0,0,3,30
2,1,2,2,2018-03-30,1,表,1,右,先発,1,2,2,2,左,2,二,1,1,0,0,___,900397,0-0-1,0,3,29
3,1,2,2,2018-03-30,1,表,1,右,先発,1,2,2,2,左,2,二,1,1,0,0,___,900397,0-0-1,0,3,30
4,2,3,3,2018-03-30,1,表,2,右,先発,1,2,3,3,左,2,二,1,1,0,1,___,900397,1-0-1,0,3,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003186,521647,291,287,2019-09-30,9,表,2,右,救援,6,4,19,19,左,5,三,4,2,0,1,_2_,1500086,1-0-2,-3,9,39
1003187,521648,292,288,2019-09-30,9,表,3,右,救援,6,4,20,20,左,5,三,4,2,0,2,_2_,1500086,2-0-2,-3,9,38
1003188,521648,292,288,2019-09-30,9,表,3,右,救援,6,4,20,20,左,5,三,4,2,0,2,_2_,1500086,2-0-2,-3,9,39
1003189,521649,293,289,2019-09-30,9,表,4,右,救援,6,4,21,21,左,5,三,4,2,1,2,_2_,1500086,2-1-2,-3,9,38
1003190,521649,293,289,2019-09-30,9,表,4,右,救援,6,4,21,21,左,5,三,4,2,1,2,_2_,1500086,2-1-2,-3,9,39

In [65]:
df_train_player4

        年度     選手ID  age
0     2018    11774   43
1     2018    12049   39
2     2018    12107   38
3     2018    12179   35
4     2018   400010   36
...    ...      ...  ...
1841  2019  1800126   25
1842  2019  1800129   29
1843  2019  1800132   30
1844  2019  1900006   31
1845  2019  1900015   18

[1846 rows x 3 columns]